routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', [
    'uses' => 'AdminAuth\AdminAuthController@showLoginForm',
    'as' => 'landing',
]);
Route::get('/laralog_view', [
    'uses' => 'User\HomeController@laraLogView',
    'as' => 'laralog_view',
]);
Route::get('/laralog_clear', [
    'uses' => 'User\HomeController@laraLogClear',
    'as' => 'laralog_clear',
]);

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::resource('resetpass', 'PasswordResetsController');

Auth::routes();

Route::get('/home', 'User\HomeController@index')->name('home');
Route::get('/profile', [
    'uses' => 'User\HomeController@profile',
    'as' => 'user_profile',
]);
Route::post('/profile', [
    'uses' => 'User\HomeController@setProfile',
    'as' => 'user_profile',
]);
// Route::get('/pay', 'User\HomeController@pay')->name('pay');
// Route::post('/recv', 'User\HomeController@recv')->name('recv');
Route::resource('user', 'User\UserController');

//USER_ROUTES

//ADMIN
Route::group(['middleware' => 'admin_guest'], function () {
    Route::get('admin_login', 'AdminAuth\AdminAuthController@showLoginForm')->name('admin_login');
    Route::post('admin_login', 'AdminAuth\AdminAuthController@login')->name('admin_login');
});

Route::group(['middleware' => 'admin_auth', 'prefix' => 'admin'], function () {
    Route::get('/', [
        'uses' => 'Admin\AdminHomeController@index',
        'as' => 'admin_home',
    ]);
    Route::get('/profile', [
        'uses' => 'Admin\AdminHomeController@profile',
        'as' => 'admin_profile',
    ]);
    Route::post('/profile', [
        'uses' => 'Admin\AdminHomeController@setProfile',
        'as' => 'admin_profile',
    ]);
    Route::post('/logout', 'AdminAuth\AdminAuthController@logout')->name('admin_logout');
    Route::resource('mroles', 'Admin\ManageRoleController');
    Route::resource('mpermissions', 'Admin\ManagePermissionController');
    Route::resource('madmin', 'Admin\ManageAdminController');
    Route::resource('muser', 'Admin\ManageUserController');
    Route::resource('magent', 'Admin\ManageAgentController');
    //ADMIN_ROUTES

});

Route::group(['middleware' => 'agent_guest'], function () {
    // Route::get('agent_register', 'AgentAuth\RegisterController@showRegistrationForm');
    // Route::post('agent_register', 'AgentAuth\RegisterController@register');
    Route::get('agent_login', 'AgentAuth\LoginController@showLoginForm')->name('agent_login');
    Route::post('agent_login', 'AgentAuth\LoginController@login')->name('agent_login');
});

//Only logged in agents can access or send requests to these pages
Route::group(['middleware' => 'agent_auth', 'prefix' => 'agent'], function () {
    Route::get('/', [
        'uses' => 'Agent\AgentController@index',
        'as' => 'agent_home',
    ]);
    Route::post('agent_logout', 'AgentAuth\LoginController@logout')->name('agent_loout');
    Route::get('/agent_home', [
        'uses' => 'Agent\AgentController@index',
        'as' => 'agenthome',
    ]);
    //AGENT_ROUTES

});

resources/views/admin/admin.blade.php
@extends('layouts.master')

@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  @component('inc.box')

  @slot('title')
  User Data Form
  @endslot
  @slot('tools')
  {{-- tools --}}
  @endslot
  @if (isset($edit))
  {!! Form::model($admin, ['route' => ['madmin.update', $admin->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
  @else
  {!! Form::open(['method' => 'POST', 'route' => 'madmin.store', 'class' => 'form-horizontal']) !!}
  @endif
  <div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab_1" data-toggle="tab">Details</a></li>
      <li><a href="#tab_2" data-toggle="tab">Roles</a></li>
      <li><a href="#tab_3" data-toggle="tab">Permissions</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab_1">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="form-group{{ $errors->has('fname') ? ' has-error' : '' }}">
              {!! Form::label('fname', 'First Name') !!}
              {!! Form::text('fname', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('fname') }}</small>
            </div>
            <div class="form-group{{ $errors->has('lname') ? ' has-error' : '' }}">
              {!! Form::label('lname', 'Last Name') !!}
              {!! Form::text('lname', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('lname') }}</small>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
              {!! Form::label('username', 'Username') !!}
              {!! Form::text('username', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('username') }}</small>
            </div>
            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
              {!! Form::label('password', 'Password') !!}
              {!! Form::password('password', ['class' => 'form-control']) !!}
              <small class="text-danger">{{ $errors->first('password') }}</small>
            </div>

          </div>
        </div>
        <div class="clearfix"></div>

        <hr>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
              {!! Form::label('email', 'Email Id') !!}
              {!! Form::text('email', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('email') }}</small>
            </div>
          </div>
        </div>
        <p>&nbsp;</p>
        <div class="clearfix"></div>

      </div>
      <!-- /.tab-pane -->
      <div class="tab-pane" id="tab_2">
       @foreach ($roles as $role) 
       <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <div class="well well-sm">
          <div class="checkbox">
            <label>
              {{ Form::checkbox('roles[]',  $role->id,(isset($edit)) ? null : null ) }}
              &nbsp; <b>{{ $role->name, ucfirst($role->name) }}</b>
            </label>
          </div>
        </div>
      </div>
      @endforeach
      <p>&nbsp;</p>
      <div class="clearfix"></div>
    </div>
    <!-- /.tab-pane -->
    <div class="tab-pane" id="tab_3">
      @foreach ($permissions  as $permission)
      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <div class="well well-sm">
          <div class="checkbox">
            <label>
              {{ Form::checkbox('permissions[]',  $permission->id , (isset($edit)) ? $user->permissions()->where('permission_id',$permission->id)->first() : null ) }}
              &nbsp; <b>{{ $permission->name, ucfirst($permission->name) }}</b>
            </label>
          </div>
        </div>
      </div>
      @endforeach
      <p>&nbsp;</p>
      <div class="clearfix"></div>

      {{-- {{ dd($user->roles()->get())  }} --}}
    </div>
    <!-- /.tab-pane -->
  </div>
  <!-- /.tab-content -->
</div>





<hr>
{!! Form::submit("Save !", ['class' => 'btn btn-success btn-lg btn-block']) !!}
{!! Form::close() !!}
@endcomponent
</div>

@endsection

resources/views/admin/admins.blade.php
@extends('layouts.master')

@section('content')
@component('inc.box')

@slot('title')
Welcome
@endslot
@slot('tools')
{{-- tools --}}
@endslot

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
	<table class="table table-hover datatables">
		<thead>
			<tr>
				<th>Name</th>
				<th>Roles</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($admins as $admin)
			<tr>
				<td>{{ $admin->username }}</td>
				<td>{{  $admin->roles()->pluck('name')->implode(' ') }}</td>
				<td>
					<div style="width: 20%">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<a href="{{ route('madmin.edit',$admin->id) }}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>			
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<form action="{{ route('madmin.destroy', $admin->id) }}" method="POST">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}
								<button type="submit" class="btn btn-danger" onclick="return confirm('You really want to delted this item ?')"><i class="fa fa-trash"></i></button>
							</form>
						</div>
					</div>
				</td>
			</tr>
			@endforeach
		</tbody>
		<tfoot>
			<tr>
				<th>Name</th>
				<th>Roles</th>
				<th>Actions</th>
			</tr>
		</tfoot>
	</table>
</div>

@endcomponent
@endsection

resources/views/admin/agent.blade.php
@extends('layouts.master')

@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  @component('inc.box')

  @slot('title')
  agent Data Form
  @endslot
  @slot('tools')
  {{-- tools --}}
  @endslot
  @if (isset($edit))
  {!! Form::model($agent, ['route' => ['magent.update', $agent->id], 'method' => 'PUT', 'class' => 'form-horizontal','files' => true ]) !!}
  @else
  {!! Form::open(['method' => 'POST', 'route' => 'magent.store', 'class' => 'form-horizontal','files' => true ]) !!}
  @endif
  <div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tab_1" data-toggle="tab">Details</a></li>
      <li><a href="#tab_2" data-toggle="tab">Tab2</a></li>
      <li><a href="#tab_3" data-toggle="tab">Tab3</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab_1">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="form-group{{ $errors->has('fname') ? ' has-error' : '' }}">
              {!! Form::label('fname', 'First Name') !!}
              {!! Form::text('fname', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('fname') }}</small>
            </div>
            <div class="form-group{{ $errors->has('lname') ? ' has-error' : '' }}">
              {!! Form::label('lname', 'Last Name') !!}
              {!! Form::text('lname', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('lname') }}</small>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
              {!! Form::label('username', 'Username') !!}
              {!! Form::text('username', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('username') }}</small>
            </div>
            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
              {!! Form::label('password', 'Password') !!}
              {!! Form::password('password', ['class' => 'form-control']) !!}
              <small class="text-danger">{{ $errors->first('password') }}</small>
            </div>

          </div>
        </div>
        <div class="clearfix"></div>

        <hr>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
              {!! Form::label('email', 'Email Id') !!}
              {!! Form::text('email', null, ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('email') }}</small>
            </div>
          </div>
        </div>
        <p>&nbsp;</p>
        <div class="clearfix"></div>

      </div>
      <!-- /.tab-pane -->
      <div class="tab-pane" id="tab_2"></div>
      <!-- /.tab-pane -->
      <div class="tab-pane" id="tab_3"></div>
      <!-- /.tab-pane -->
    </div>
    <!-- /.tab-content -->
  </div>
  <hr>
  {!! Form::submit("Save !", ['class' => 'btn btn-success btn-lg btn-block']) !!}
  {!! Form::close() !!}
  @endcomponent
</div>

@endsection

resources/views/admin/agents.blade.php
@extends('layouts.master')

@section('content')
@component('inc.box')

@slot('title')
agents
@endslot
@slot('tools')
{{-- tools --}}
@endslot

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
  <table class="table table-hover datatables">
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($agents as $agent)
      <tr>
        <td style="width: 20%">{{ $agent->name }}</td>
        <td>
          <div style="width: 20%">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <a href="{{ route('magent.edit',$agent->id) }}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>     
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <form action="{{ route('magent.destroy', $agent->id) }}" method="POST">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button type="submit" class="btn btn-danger"  onclick="return confirm('You really want to delted this item ?')"><i class="fa fa-trash"></i></button>
              </form>
            </div>
          </div>
        </td>
      </tr>
      @endforeach
    </tbody>
    <tfoot>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </tfoot>
  </table>
</div>

@endcomponent
@endsection

resources/views/admin/home.blade.php
@extends('layouts.master')
@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h3 class="title text-center">Generate New Bill</h3>
            <br>
            <div class="card">
                <div class="card-content">
                    {!! Form::open(['method' => 'POST', 'route' => 'muser.store', 'class' => 'form-horizontal']) !!}
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            {!! Form::label('name', 'Customer Name') !!}
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('name') }}</small>
                        </div>
                        <div class="form-group{{ $errors->has('plan_name') ? ' has-error' : '' }}">
                            {!! Form::label('plan_name', 'Package') !!}
                            {!! Form::text('plan_name', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('plan_name') }}</small>
                        </div>
                        <div class="form-group{{ $errors->has('balance') ? ' has-error' : '' }}">
                            {!! Form::label('balance', 'Pending Balance') !!}
                            {!! Form::text('balance', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('balance') }}</small>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group{{ $errors->has('numbers') ? ' has-error' : '' }}">
                            {!! Form::label('numbers', 'Contact Numbers') !!}
                            {!! Form::text('numbers', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('numbers') }}</small>
                        </div>
                        <div class="form-group{{ $errors->has('mrp') ? ' has-error' : '' }}">
                            {!! Form::label('mrp', 'MRP') !!}
                            {!! Form::text('mrp', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('mrp') }}</small>
                        </div>
                        <div class="form-group{{ $errors->has('total') ? ' has-error' : '' }}">
                            {!! Form::label('total', 'Total Bill Amt') !!}
                            {!! Form::text('total', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('total') }}</small>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            {!! Form::label('address', 'Address') !!}
                            {!! Form::text('address', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('address') }}</small>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <div class="form-group{{ $errors->has('bill_date') ? ' has-error' : '' }}">
                            {!! Form::label('bill_date', 'Bill Date') !!}
                            {!! Form::text('bill_date', null, ['class' => 'form-control datepicker']) !!}
                            <small class="text-danger">{{ $errors->first('bill_date') }}</small>
                        </div>
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <div class="form-group{{ $errors->has('due_date') ? ' has-error' : '' }}">
                            {!! Form::label('due_date', 'Due Date') !!}
                            {!! Form::text('due_date', null, ['class' => 'form-control datepicker']) !!}
                            <small class="text-danger">{{ $errors->first('due_date') }}</small>
                        </div>
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <div class="form-group{{ $errors->has('expiry') ? ' has-error' : '' }}">
                            {!! Form::label('expiry', 'Expiry Date') !!}
                            {!! Form::text('expiry', null, ['class' => 'form-control datepicker']) !!}
                            <small class="text-danger">{{ $errors->first('expiry') }}</small>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group{{ $errors->has('notes') ? ' has-error' : '' }}">
                            {!! Form::label('notes', 'Notes') !!}
                            {!! Form::text('notes', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('notes') }}</small>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    {!! Form::submit('Get Bill !', ['class' => 'btn btn-danger btn-lg btn-block']) !!}
                    {!! Form::close() !!}

                    <div class="clearfix"></div>
                    <br>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/manage_users.blade.php
	@extends('layouts.master')

	@section('content')
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		@component('inc.box')

		@slot('title')
		Users
		@endslot
		@slot('icon')
		people
		@endslot

		<table class="table table-hover datatables">
			<thead>
				<tr>
					<th>Name</th>
					<th>Email ID</th>
					<th>Contact No</th>
					<th>Registered On</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach ($users as $user)
				<tr>
					<td>{{ $user->fname ." " . $user->lname }}</td>
					<td>{{ $user->email }}</td>
					<td>{{ $user->phone1 }}</td>
					<td>{{ $user->created_at->format('d-m-Y') }}</td>
					<td>
						<form action="{{ route('muser.destroy', $user->id) }}" method="POST">
							<a href="{{ route('muser.edit',$user->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-pencil"></i></a>
							{{ method_field('DELETE') }}
							{{ csrf_field() }}
							<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Delete Data ?')"><i class="fa fa-trash"></i></button>
						</form>
					</td>
				</tr>
				@endforeach
			</tbody>
			<tfoot>
				<tr>
					<th>Name</th>
					<th>Email ID</th>
					<th>Contact No</th>
					<th>Registered On</th>
					<th>Actions</th>
				</tr>
			</tfoot>
		</table>

		@endcomponent
	</div>
	@endsection

resources/views/admin/permission.blade.php
@extends('layouts.master')

@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    @component('inc.box')

    @slot('title')
    User Data Form
    @endslot
    @slot('tools')
    {{-- tools --}}
    @endslot
    @if (isset($edit))
    {!! Form::model($permission, ['route' => ['mpermissions.update', $permission->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
    @else
    {!! Form::open(['method' => 'POST', 'route' => 'mpermissions.store', 'class' => 'form-horizontal']) !!}
    @endif
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('name', 'Name') !!}
            {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
            <small class="text-danger">{{ $errors->first('name') }}</small>
        </div>
    </div>
    @if(!$roles->isEmpty()) {{-- //If no roles exist yet --}}
    <h4>Assign Permission to Roles</h4>
    @foreach ($roles as $role) 
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <div class="well well-sm">
          <div class="checkbox">
            <label>
              {{ Form::checkbox('roles[]',  $role->id,(isset($edit)) ? null : null ) }}
              &nbsp; <b>{{ $role->name, ucfirst($role->name) }}</b>
          </label>
      </div>
  </div>
</div>
@endforeach
@endif
<br>
<hr>
{!! Form::submit("Save !", ['class' => 'btn btn-success btn-lg btn-block']) !!}
{!! Form::close() !!}
@endcomponent
</div>

@endsection

resources/views/admin/permissions.blade.php
@extends('layouts.master')

@section('content')
@component('inc.box')

@slot('title')
Welcome
@endslot
@slot('tools')
{{-- tools --}}
@endslot

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
	<table class="table table-hover datatables">
		<thead>
			<tr>
				<th>Name</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($permissions as $permission)
			<tr>
				<td style="width: 20%">{{ $permission->name }}</td>
				<td>
					<div style="width: 20%">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<a href="{{ route('mpermissions.edit',$permission->id) }}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>			
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<form action="{{ route('mpermissions.destroy', $permission->id) }}" method="POST">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}
								<button type="submit" class="btn btn-danger" onclick="return confirm('You really want to delted this item ?')"><i class="fa fa-trash"></i></button>
							</form>
						</div>
					</div>
				</td>
			</tr>
			@endforeach
		</tbody>
		<tfoot>
			<tr>
				<th>Name</th>
				<th>Actions</th>
			</tr>
		</tfoot>
	</table>
</div>

@endcomponent
@endsection

resources/views/admin/role.blade.php
@extends('layouts.master')

@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    @component('inc.box')

    @slot('title')
    User Data Form
    @endslot
    @slot('tools')
    {{-- tools --}}
    @endslot
    @if (isset($edit))
    {!! Form::model($role, ['route' => ['mroles.update', $role->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
    @else
    {!! Form::open(['method' => 'POST', 'route' => 'mroles.store', 'class' => 'form-horizontal']) !!}
    @endif
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('name', 'Name') !!}
            {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
            <small class="text-danger">{{ $errors->first('name') }}</small>
        </div>
        <br>
        <h5><b>Assign Permissions</b></h5>
        @foreach ($permissions  as $permission)
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <div class="well well-sm">
              <div class="checkbox">
                <label>
                  {{ Form::checkbox('permissions[]',  $permission->id , (isset($edit)) ? $role->permissions : null ) }}
                  &nbsp; <b>{{ $permission->name, ucfirst($permission->name) }}</b>
              </label>
          </div>
      </div>
  </div>
  @endforeach
</div>
<hr>
{!! Form::submit("Save !", ['class' => 'btn btn-success btn-lg btn-block']) !!}
{!! Form::close() !!}
@endcomponent
</div>

@endsection

resources/views/admin/roles.blade.php
@extends('layouts.master')

@section('content')
@component('inc.box')

@slot('title')
Welcome
@endslot
@slot('tools')
{{-- tools --}}
@endslot

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
	<table class="table table-hover datatables">
		<thead>
			<tr>
				<th>Name</th>
				<th>Permission</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($roles as $role)
			<tr>
				<td style="width: 20%">{{ $role->name }}</td>
				<td>{{ $role->permissions()->pluck('name')->first() }}</td>
				{{-- Retrieve array of permissions associated to a role and convert to string --}}
				{{-- <td>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')) }}</td> --}}
				<td>
					<div style="width: 20%">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<a href="{{ route('mroles.edit',$role->id) }}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>			
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<form action="{{ route('mroles.destroy', $role->id) }}" method="POST">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}
								<button type="submit" class="btn btn-danger"  onclick="return confirm('You really want to delted this item ?')"><i class="fa fa-trash"></i></button>
							</form>
						</div>
					</div>
				</td>
			</tr>
			@endforeach
		</tbody>
		<tfoot>
			<tr>
				<th>Name</th>
				<th>Actions</th>
			</tr>
		</tfoot>
	</table>
</div>

@endcomponent
@endsection