routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', [
    'uses' => 'AdminAuth\AdminAuthController@showLoginForm',
    'as' => 'landing',
]);
Route::get('/laralog_view', [
    'uses' => 'User\HomeController@laraLogView',
    'as' => 'laralog_view',
]);
Route::get('/laralog_clear', [
    'uses' => 'User\HomeController@laraLogClear',
    'as' => 'laralog_clear',
]);

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::resource('resetpass', 'PasswordResetsController');

Auth::routes();

Route::get('/home', 'User\HomeController@index')->name('home');
Route::get('/profile', [
    'uses' => 'User\HomeController@profile',
    'as' => 'user_profile',
]);
Route::post('/profile', [
    'uses' => 'User\HomeController@setProfile',
    'as' => 'user_profile',
]);
// Route::get('/pay', 'User\HomeController@pay')->name('pay');
// Route::post('/recv', 'User\HomeController@recv')->name('recv');
Route::resource('user', 'User\UserController');

//USER_ROUTES

//ADMIN
Route::group(['middleware' => 'admin_guest'], function () {
    Route::get('admin_login', 'AdminAuth\AdminAuthController@showLoginForm')->name('admin_login');
    Route::post('admin_login', 'AdminAuth\AdminAuthController@login')->name('admin_login');
});

Route::group(['middleware' => 'admin_auth', 'prefix' => 'admin'], function () {
    Route::get('/', [
        'uses' => 'Admin\AdminHomeController@index',
        'as' => 'admin_home',
    ]);
    Route::get('/profile', [
        'uses' => 'Admin\AdminHomeController@profile',
        'as' => 'admin_profile',
    ]);
    Route::post('/profile', [
        'uses' => 'Admin\AdminHomeController@setProfile',
        'as' => 'admin_profile',
    ]);
    Route::post('/logout', 'AdminAuth\AdminAuthController@logout')->name('admin_logout');
    Route::resource('mroles', 'Admin\ManageRoleController');
    Route::resource('mpermissions', 'Admin\ManagePermissionController');
    Route::resource('madmin', 'Admin\ManageAdminController');
    Route::resource('muser', 'Admin\ManageUserController');
    Route::resource('magent', 'Admin\ManageAgentController');
    //ADMIN_ROUTES

});

Route::group(['middleware' => 'agent_guest'], function () {
    // Route::get('agent_register', 'AgentAuth\RegisterController@showRegistrationForm');
    // Route::post('agent_register', 'AgentAuth\RegisterController@register');
    Route::get('agent_login', 'AgentAuth\LoginController@showLoginForm')->name('agent_login');
    Route::post('agent_login', 'AgentAuth\LoginController@login')->name('agent_login');
});

//Only logged in agents can access or send requests to these pages
Route::group(['middleware' => 'agent_auth', 'prefix' => 'agent'], function () {
    Route::get('/', [
        'uses' => 'Agent\AgentController@index',
        'as' => 'agent_home',
    ]);
    Route::post('agent_logout', 'AgentAuth\LoginController@logout')->name('agent_loout');
    Route::get('/agent_home', [
        'uses' => 'Agent\AgentController@index',
        'as' => 'agenthome',
    ]);
    //AGENT_ROUTES

});

resources/views/OLDlayouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/OLDlayouts/foot.blade.php
<!-- jQuery 2.2.3 -->
<script src="{{ url('ui/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
$.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ url('ui/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script> --}}
{{-- <script src="ui/plugins/morris/morris.min.js"></script> --}}
<!-- Sparkline -->
{{-- <script src="ui/plugins/sparkline/jquery.sparkline.min.js"></script> --}}
<!-- jvectormap -->
{{-- <script src="ui/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script> --}}
{{-- <script src="ui/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script> --}}
<!-- jQuery Knob Chart -->
{{-- <script src="ui/plugins/knob/jquery.knob.js"></script> --}}
<!-- daterangepicker -->
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script> --}}
{{-- <script src="ui/plugins/daterangepicker/daterangepicker.js"></script> --}}
<!-- datepicker -->
<script src="{{ url('ui/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
{{-- <script src="ui/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script> --}}
<!-- Slimscroll -->
<script src="{{ url('ui/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ url('ui/plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url('ui/plugins/select2/select2.full.min.js') }}"></script>

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="ui/dist/js/pages/dashboard.js"></script> --}}
<!-- AdminLTE for demo purposes -->
{{-- <script src="ui/dist/js/demo.js"></script> --}}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/se-1.2.2/datatables.min.js"></script>

<script src="{{ url('js/notify.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url('ui/dist/js/app.min.js') }}"></script>

{{-- <script src="{{ url('materialui/dist/js/material.min.js') }}"></script>
<script src="{{ url('materialui/dist/js/ripples.min.js') }}"></script> --}}

<script  type="text/javascript">
$(document).ready(function() {
	$('.notifytest').notify("TEST",{ 
		position:"bottom left",
		arrowShow: true,
	});
	$(".select2").select2({
		tags:[],
		tokenSeparators: [";"],

	});
	$(".select2-selection").on("focus", function () {
		$(this).parent().parent().prev().select2("open");
	});
	$('.select2-search > input.select2-search__field').on('keyup', function(e) {
		if(e.keyCode === 13 || e.keyCode == 9) 
			addToList($(this).val());
	});
	$('.datatables tfoot th').each( function () {
		var title = $(this).text();
		if (title =="Actions") {
			return;
		}
		$(this).html( '<input type="text" placeholder="&#x1F50D; '+title+'" style="width:100%"/>' );
		$(this).css("width","50px");

	} );
	
	$('.datatables tbody td').each( function () {
		var count_td = $('.datatables tbody tr:first>td').length
		var td_width = 90 / count_td		
		console.log(td_width);
		$(this).css("width",td_width+"%");

	} );
	window.mydatatable = $('.datatables').DataTable({
		dom: 'lBfrtip',
		buttons: [
		'colvis',{
			extend: 'copy',
			exportOptions: {
				columns: ':visible'
			}
		},
		{
			extend: 'csv',
			exportOptions: {
				columns: ':visible'
			}
		},
		{
			extend: 'excel',
			exportOptions: {
				columns: ':visible'
			}
		},
		{
			extend: 'pdf',
			orientation: 'landscape',
			pageSize: 'A4',
			download: 'open',
			exportOptions: {
				columns: ':visible'
			}
		},
		{
			extend: 'print',
			exportOptions: {
				columns: ':visible'
			}
		},
		],
		colReorder: true
	});
	mydatatable.columns().every( function () {
		var that = this;

		$( 'input', this.footer() ).on( 'keyup change', function () {
			if ( that.search() !== this.value ) {
				that
				.search( this.value )
				.draw();
			}
		} );
	} );



});
</script>
@yield('scripts')

{{-- 

	Dropzone.options.myDropzone = {
		url: "{{ route('uploadlr') }}",
		headers: {  'X-CSRF-TOKEN': "{{ csrf_token() }}" , 'order-id': order_id },
		acceptedFiles: ".jpeg,.jpg,.png,.gif,.pdf",
		autoProcessQueue: false,
		uploadMultiple: true,
		parallelUploads: 1,
		init: function() {
			var myDropzone = this;
			url: "{{ route('uploadlr') }}",
			document.getElementById("submit_lr").addEventListener("click", function(e) {
				e.preventDefault();
				e.stopPropagation();
				myDropzone.processQueue();
			});
			this.on("addedfile", function(file) {
				var removeButton = Dropzone.createElement('<a class="dz-remove">Remove file</a>');
				var _this = this;
				lrno = file.caption == undefined ? "" : file.caption;
				courier = file.caption == undefined ? "" : file.caption;
				invoice = file.caption == undefined ? "" : file.caption;
				file._captionLRLabel = Dropzone.createElement("<p>LR Number:</p>")
				file._captionLRNo = Dropzone.createElement("<input id='"+file.filename+"' type='text' name='lr_no' value="+lrno+" >");
				file._captionCourierLabel = Dropzone.createElement("<p>Courier:</p>")
				file._captionCourierName = Dropzone.createElement("<input id='"+file.filename+"' type='text' name='courier' value="+courier+" >");
				file._captionInvoiceNoLabel = Dropzone.createElement("<p>Invoice Number:</p>")
				file._captionInvoiceNoName = Dropzone.createElement("<input id='"+file.filename+"' type='text' name='invoice' value="+invoice+" >");
				file.previewElement.appendChild(file._captionLRLabel);
				file.previewElement.appendChild(file._captionLRNo);
				file.previewElement.appendChild(file._captionCourierLabel);
				file.previewElement.appendChild(file._captionCourierName);
					// file.previewElement.appendChild(file._captionInvoiceNoLabel);
					// file.previewElement.appendChild(file._captionInvoiceNoName);
					removeButton.addEventListener("click", function(e) {
						e.preventDefault();
						e.stopPropagation();
						var fname = file.previewElement.querySelector('[data-dz-name]').innerHTML;
						var fileInfo = new Array();
						fileInfo['name']=fname;
						$.ajax({
							type: "POST",
							url: "{{ route('deletelr') }}",
							data: {file: fname, "_token": "{{ csrf_token() }}"},
							beforeSend: function () {
							},
							success: function (response) {
								if (response == 'success')
									alert('deleted');
							},
							error: function (data) {
								$('.error').text(data);
								console.log(data)
								// alert("error");
							}
						});
						_this.removeFile(file);
					});
					file.previewElement.appendChild(removeButton);
				});
this.on(
	"sending", function(file, xhr, formData){
		formData.append('lr_no',file._captionLRNo.value);
		formData.append('courier',file._captionCourierName.value);
		formData.append('invoice',file._captionInvoiceNoName.value);
	})
this.on("success", function(file,response) {
	console.log(response)
	mytable.row.add([ 
		'<input type="text" name="lr_no" id="inputLr_no" class="form-control" value="'+response.data.lr_no+'">',
		'<input type="text" name="courier" id="inputLr_no" class="form-control" value="'+response.data.courier+'">',
		'<input type="text" name="invoice_no" id="inputLr_no" class="form-control" value="'+response.data.invoice_no+'">',
		(response.invoice !== null) ?
		'<a href="'+response.invoice+'" target="_blank" class="btn btn-large btn-block btn-success">View Invoice</a>'
		:
		'<a href="#" target="_blank" class="btn btn-large btn-block btn-warning">NOT FOUND</a>'
		,
		'<a href="{{ url("/") }}/'+response.data.lr_receipt+'" target="_blank" class="btn btn-large btn-block btn-success">View LR</a>',
		'<a type="button" class="btn btn-warning editlr" data-lrid="'+response.data.id+'"><i class="fa fa-fw fa-pencil"></i></a><a type="button" class="btn btn-danger deletemylr" data-lrid="'+response.data.id+'"><i class="fa fa-fw fa-trash"></i></a>'
		]).draw();
	var i = myDropzone.getQueuedFiles().length;
	while (i > 0) {
		myDropzone.processQueue();
		i--;
	};
	file.previewElement.querySelector("[data-dz-name]").innerHTML  = response.filename;
});
}
}


 --}}

resources/views/OLDlayouts/footer.blade.php
  <footer class="main-footer">
    <strong>Copyright &copy; {{ date('Y') }} <a href="http://#">App</a>.</strong> All rights
    reserved.
  </footer>

resources/views/OLDlayouts/lmenu.blade.php
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ url('ui/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ $user->fname . " " . $user->lname }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MENU</li>
        @if (Auth::check())
        <li>
          <a href="{{ route('home') }}">
            <i class="fa fa-envelope"></i> <span>Home</span>
          </a>
        </li>
        @endif
        @if (Auth::guard('admin')->check())
        <li>
          <a href="{{ route('admin_home') }}">
            <i class="fa fa-envelope"></i> <span>Home</span>
          </a>
        </li>   
        <li class="treeview">
          <a href="#">
            <i class="fa fa-user"></i>
            <span>Admins &amp; Permissions</span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('madmin.create') }}"><i class="fa fa-circle-o"></i> Add Admin</a></li>
            <li><a href="{{ route('madmin.index') }}"><i class="fa fa-circle-o"></i> View Admins</a></li>
            <li><a href="{{ route('mroles.create') }}"><i class="fa fa-circle-o"></i> Add Role</a></li>
            <li><a href="{{ route('mroles.index') }}"><i class="fa fa-circle-o"></i> View Roles</a></li>
            <li><a href="{{ route('mpermissions.create') }}"><i class="fa fa-circle-o"></i> Add Permission</a></li>
            <li><a href="{{ route('mpermissions.index') }}"><i class="fa fa-circle-o"></i> View Permissions</a></li>
          </ul>
        </li>     
        @endif
      </ul>
      {{-- <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
            <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Layout Options</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">4</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
            <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
            <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
            <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
          </ul>
        </li>
        <li>
          <a href="pages/widgets.html">
            <i class="fa fa-th"></i> <span>Widgets</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-green">new</small>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Charts</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
            <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
            <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
            <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-laptop"></i>
            <span>UI Elements</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
            <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
            <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
            <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
            <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
            <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-edit"></i> <span>Forms</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
            <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
            <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-table"></i> <span>Tables</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
            <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
          </ul>
        </li>
        <li>
          <a href="pages/calendar.html">
            <i class="fa fa-calendar"></i> <span>Calendar</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">3</small>
              <small class="label pull-right bg-blue">17</small>
            </span>
          </a>
        </li>
        <li>
          <a href="pages/mailbox/mailbox.html">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-folder"></i> <span>Examples</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
            <li><a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
            <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
            <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
            <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
            <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
            <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
            <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
            <li><a href="pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li>
              <a href="#"><i class="fa fa-circle-o"></i> Level One
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                <li>
                  <a href="#"><i class="fa fa-circle-o"></i> Level Two
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                  </a>
                  <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          </ul>
        </li>
        <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
      </ul> --}}
    </section>
    <!-- /.sidebar -->
  </aside>